SELECT 
    CAST(gid.game_id AS INTEGER) AS GAME_ID,
    CAST(ply.player_id AS INTEGER) AS PLAYER_ID,
    CAST(ftsy.PLAYER_NAME AS STRING) AS PLAYER_NAME,
    CAST(teams.team_id AS INTEGER) AS TEAM_ID,
    CAST(ftsy.TEAM_NAME AS STRING) AS TEAM_NAME,
    CAST(ftsy.TEAM_ABBREVIATION AS STRING) AS TEAM_ABBREVIATION,
    CAST(ftsy.JERSEY_NUM AS INTEGER) AS JERSEY_NUM,
    CAST(ftsy.PLAYER_POSITION AS STRING) AS PLAYER_POSITION,
    CAST(ftsy.LOCATION AS STRING) AS LOCATION,
    CAST(ftsy.FAN_DUEL_PTS AS FLOAT64) AS FAN_DUEL_PTS,
    CAST(ftsy.NBA_FANTASY_PTS AS FLOAT64) AS NBA_FANTASY_PTS,
    CAST(ftsy.USG_PCT AS FLOAT64) AS USG_PCT,
    CAST(ftsy.MIN AS FLOAT64) AS MIN,
    CAST(ftsy.FGM AS INTEGER) AS FGM,
    CAST(ftsy.FGA AS INTEGER) AS FGA,
    CAST(ftsy.FG_PCT AS FLOAT64) AS FG_PCT,
    CAST(ftsy.FG3M AS INTEGER) AS FG3M,
    CAST(ftsy.FG3A AS INTEGER) AS FG3A,
    CAST(ftsy.FG3_PCT AS FLOAT64) AS FG3_PCT,
    CAST(ftsy.FTM AS INTEGER) AS FTM,
    CAST(ftsy.FTA AS INTEGER) AS FTA,
    CAST(ftsy.FT_PCT AS FLOAT64) AS FT_PCT,
    CAST(ftsy.OREB AS INTEGER) AS OREB,
    CAST(ftsy.DREB AS INTEGER) AS DREB,
    CAST(ftsy.REB AS INTEGER) AS REB,
    CAST(ftsy.AST AS INTEGER) AS AST,
    CAST(ftsy.TOV AS INTEGER) AS TOV,
    CAST(ftsy.STL AS INTEGER) AS STL,
    CAST(ftsy.BLK AS INTEGER) AS BLK,
    CAST(ftsy.BLKA AS INTEGER) AS BLKA,
    CAST(ftsy.PF AS INTEGER) AS PF,
    CAST(ftsy.PFD AS INTEGER) AS PFD,
    CAST(ftsy.PTS AS INTEGER) AS PTS,
    CAST(ftsy.PLUS_MINUS AS INTEGER) AS PLUS_MINUS
FROM `nfl1-447014.nba_staging.nba_daily_stats` ftsy
LEFT JOIN `nfl1-447014.nba_marts.dim_nba_players` ply
    ON ply.player_id = ftsy.PLAYER_ID
LEFT JOIN `nfl1-447014.nba_marts.dim_nba_teams` teams
    ON teams.team_id = ftsy.TEAM_ID
LEFT JOIN `nfl1-447014.nba_marts.dim_game_ids` gid
    ON gid.game_id = ftsy.GAME_ID